name: ci

on:
  push:
    branches:
      - main 
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags


jobs:
  build:
    permissions:
      contents: write
    defaults:
      run:
        working-directory: go/src/github.com/exam-rncp/payment
    runs-on: ubuntu-latest
    env:
      GROUP: f3lin 
      COMMIT: ${{ github.sha }}
      REPO: payment
      GO_VERSION: 1.7
      GOPATH: /home/runner/work/payment/payment/go/
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: go/src/github.com/exam-rncp/payment

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }} 

    - name: Install prereqs
      run: |
        go get -u github.com/FiloSottile/gvt
        gvt restore

    - name: Build
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh

    - name: Unit test
      run: |
        chmod +x test/test.sh
        ./test/test.sh unit.py

    - name: Container test
      run: |
        ./test/test.sh container.py
  
    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        chmod +x scripts/git_update_tag.sh
        bash scripts/git_update_tag.sh -v patch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker images tag
      env:
        TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker image tag $GROUP/$REPO:$COMMIT $GROUP/$REPO:$TAG

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.GROUP }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push user to Docker Hub
      env:
        TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        make release
        docker push $GROUP/$REPO:$TAG